version: '2'
services:

  www:
    container_name: cistatus
    restart: always
    image: sshnaidm/sova:rdoci
    ports:
      - "80:8090"
    volumes:
      - ~/cidata:/cidata:z
      - ~/logdir:/logdir:z
    command: "-p"
